FROM ubuntu:16.04

RUN apt-get update

RUN apt-get install wget

RUN apt-get install xz.utils #To untar files with xz extension

RUN apt-get install gcc

RUN apt-get install make

RUN apt-get install g++ #to install swig from sources. Not necessary for ubuntu>=18

RUN apt-get install zlib1g-dev #for python installation

RUN apt-get install libffi-dev #for ctype in python installation

RUN apt-get install libssl-dev #vérifier si nécessaire

