FROM     mcr.microsoft.com/windows/nanoserver:1803-amd64

RUN pwd
RUN powershell curl --progress-bar --location --output hdf5/download.zip "https://www.hdfgroup.org/package/cmake-hdf5-1-12-1-zip/?wpdmdl=15723"
