name: Windows image build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'     
        required: false
        default: ''  

jobs:
  build-image:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Build and push console
        working-directory: .
        run: |
          docker login -u ${{env.USER}} -p ${{env.TOKEN}}
          docker build . --file DockerFiles/windows/Dockerfile --tag my-image-name:$(date +%s)
          docker image my-image-name:$(date +%s)
          docker push ndesassis/my-image-name:$(date +%s)
          docker logout
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#docker-compose build windows
#docker image push ndesassis/win:pygst-2022

