name: ubuntu16 image build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'     
        required: false
        default: ''  

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push console
        working-directory: .
        run: |
          docker build . --file DockerFiles/ubuntu16/Dockerfile --tag test_ubuntu16:2022
          docker images
          docker ps -a
          docker commit test_ubuntu16:2022 ndesassis/test_ubuntu16:2022
          docker images
          docker ps -a
          docker login -u ${{env.USER}} -p ${{env.TOKEN}}
          docker push ndesassis/test_ubuntu16:2022
          docker logout
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#docker-compose build windows
#docker image push ndesassis/win:pygst-2022
#$(date +%s)
